messages:
  reload-message: '&e&l[!] &eLes fichiers de configuration ont été rechargés.'
  invalid-player: '&c&l[!] &cLe joueur est invalide ou n''est pas connecté.'
  give-box: '&e&l[!] &eVous avez donner &6&lx%amount% %box% &eà &6&l%player%&e.'
  box-given: '&e&l[!] &eVous avez reçu &6&lx%amount% %box%&e.'
holo-menus:
  main:
    cancel:
      title: '&4Annuler'
      item:
        material: PLAYER_HEAD
        head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWFlMGU0ODZkYjRlYzQ5ZmYxYjUyY2ZlY2VkYTRjM2YzNmZkZTIzYzgzNWVhM2NjZmNhYWM5MzVlNDliNWYxMCJ9fX0=
    list:
      title: '&bRécompenses'
      item:
        material: PLAYER_HEAD
        head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjJjNWY3YWM3MDZiMmU4YTg3OGViZjk3MmIwN2YzZDM2NDQ5YWI3MGIwOWFjZDk3M2VlYWJiMGQ1ZmM0YTZiNCJ9fX0=
boxes:
  iron:
    name: '&b&lIron Box'
    item:
      material: PLAYER_HEAD
      head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWM5NmJlNzg4NmViN2RmNzU1MjVhMzYzZTVmNTQ5NjI2YzIxMzg4ZjBmZGE5ODhhNmU4YmY0ODdhNTMifX19
      name: '&b&lIron Box'
      lore:
      - test
      - test
      - test
      - test
    rewards:
      '1':
        type: item
        item:
          material: DIAMOND_PICKAXE
          name: Special Diamond Pickaxe
          lore:
          - test
          - test
        weight: 1
      '2':
        type: commands
        item:
          material: SUNFLOWER
          name: MONEY $10.0000
          lore:
          - test
          - test
        weight: 2
        commands:
        - eco give %player% 10000
  gold:
    name: '&b&lGold Box'
    item:
      material: PLAYER_HEAD
      head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWM5NmJlNzg4NmViN2RmNzU1MjVhMzYzZTVmNTQ5NjI2YzIxMzg4ZjBmZGE5ODhhNmU4YmY0ODdhNTMifX19
      name: '&b&lGold Box'
      lore:
      - test
      - test
      - test
      - test
    rewards:
      '1':
        type: item
        item:
          material: GOLDEN_PICKAXE
          name: Special Gold Pickaxe
          lore:
          - test
          - test
        weight: 1
      '2':
        type: commands
        item:
          material: SUNFLOWER
          name: MONEY $5.0000
          lore:
          - test
          - test
        weight: 2
        commands:
        - eco give %player% 5000